### ISSUE TITLE
it seems ok

### ISSUE THREAD

**Issue by JarvanMo** [gen0083/KotlinDaggerDataBinding#1]
there is one question I want to ask 
How can I get dataBinding compiler version programly

**Comment by JarvanMo** [comment]
there is one question I want to ask 
How can I get dataBinding compiler version programly

**Comment by imknown** [comment]
ohhh, it's you here =_ =..

- set variable like `dbc_version = 1.0-rc4` in project's `gradle,properties`.  

- then create `buildTypes.each` in module's 'build.grade' like :  
``` groovy
buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        buildTypes.each {
            it.resValue 'string', 'daya_binding_compiler_version', dbc_version
        }
    }
```

- use in java:  
``` java
String DayaBindingCompilerVersion = getString(R.string.daya_binding_compiler_version);
```

### more info here:  
https://github.com/imknown/IMKDevelopmentDaily/blob/master/2016/06/05.02_gradle%E4%B8%AD%20compile%E6%96%B9%E6%B3%95%20Java%E4%BB%A3%E7%A0%81%20%E6%8E%A7%E5%88%B6%20%E7%89%88%E6%9C%AC%E5%8F%B7.md

**Comment by JarvanMo** [comment]
Actually, I meant I didn't know the exact version number the Android-Studio used. We use DataBinding  I don't want to define  the compiler version in the project or somewhere, just get it automaticlly.

**Comment by JarvanMo** [comment]
whatever thank u

**Comment by gen0083** [comment]
I don't know what version Android Studio used.
(I think that Android Studio uses data binding compiler same version of itself...)
By the way, I checked version [here(bintray)](https://bintray.com/android/android-tools/com.android.databinding.compiler/view).
