### ISSUE TITLE
About the KAPT limitation

### ISSUE THREAD

**Issue by adi1133** [gen0083/KotlinDaggerDataBinding#2]
Thank you for posting about the limitation, does it have a youtrack issue number I can track ?

**Comment by gen0083** [comment]
No, I haven't posted this issue yet.

**Comment by adi1133** [comment]
This is the only place on the internet I found this issue documented, this should be in the kotlin issue tracker.

**Comment by gen0083** [comment]
Posted https://youtrack.jetbrains.com/issue/KT-12659
